[package]
name = "opus"
version = "0.3.0"
authors = ["Tad Hardesty <tad@platymuus.com>"]

description = "Safe Rust bindings for libopus"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["opus", "codec", "voice", "sound", "audio"]

repository = "https://github.com/SpaceManiac/opus-rs"
documentation = "https://wombat.platymuus.com/rustdoc/opus_0.2.0/"

[dependencies]
opus-sys = "0.2.0"
libc = "0.2"

[dev-dependencies]
compiletest_rs = "0.2.4"
